// REQUIRES: not-msan
// Disabling msan because it times out on CI
// RUN: %clang %s -emit-llvm %O0opt -g -c -o %t1.bc
// RUN: rm -rf %t.klee-out
// RUN: %klee --output-dir=%t.klee-out --use-forked-solver=false -max-memory=6008 --optimize=true --skip-not-lazy-initialized -output-source=true --output-stats=false --output-istats=false --write-xml-tests --write-ktests=false --xml-metadata-programfile=wrapped_btor2c-lazyMod.adding.1.prop1-back-serstep.c --xml-metadata-programhash=a18daeacf63b42ad6e1cb490555b7cdecd71ad6e58b167ed0f5626c03bc3d772 --use-sym-size-alloc=true --cex-cache-validity-cores --symbolic-allocation-threshold=8192 --function-call-reproduce=reach_error --dump-states-on-halt=all -exit-on-error-type=Assert --search=dfs --search=random-path -max-time=20 %t1.bc 2>&1 | FileCheck -check-prefix=CHECK-VERDICT %s

// RUN: test -f %t.klee-out/test000001.xml
// RUN: not test -f %t.klee-out/test000001.ktest

// CHECK-VERDICT: KLEE: WARNING: 100.00% Reachable Reachable at trace

//RUN: FileCheck %s -input-file=%t.klee-out/assembly.ll
// the only forking br is in __VERIFIER_assert
// that is, all ternary ifs are turned into `select` instructions
// CHECK: {{call.*reach_error}}
// CHECK-COUNT-11: {{ phi }}






// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2007 - 2022 Radek Pelánek
// SPDX-FileCopyrightText: 2022 The SV-Benchmarks Community
//
// SPDX-License-Identifier: Apache-2.0

// This C program is converted from Btor2 by Btor2C version bfcfb8b
//   with arguments: { architecture=64, lazy_modulo=true, use_memmove=false, unroll_inner_loops=false, shortest_type=true, diff_type=true, decimal_constant=true, zero_init=false, sra_extend_sign=true }
// Comments from the original Btor2 file:
// ; source: http://fmv.jku.at/hwmcc19/beem_btor.tar.xz
// ; Model in BTOR format generated by stepout.py 0.41
#include "klee-test-comp.c"
extern void abort(void);
void reach_error() {}

extern unsigned char __VERIFIER_nondet_uchar();
extern unsigned short __VERIFIER_nondet_ushort();
extern unsigned int __VERIFIER_nondet_uint();
extern unsigned long __VERIFIER_nondet_ulong();
void __VERIFIER_assert(int cond) { if (!(cond)) { ERROR: { reach_error(); abort(); } } }
void assume_abort_if_not(int cond) { if (!cond) { abort(); } }
int main() {
  // Defining sorts ...
  typedef unsigned char SORT_1;  // BV with 1 bits
  const SORT_1 mask_SORT_1 = (SORT_1)-1 >> (sizeof(SORT_1) * 8 - 1);
  const SORT_1 msb_SORT_1 = (SORT_1)1 << (1 - 1);
  typedef unsigned char SORT_2;  // BV with 5 bits
  const SORT_2 mask_SORT_2 = (SORT_2)-1 >> (sizeof(SORT_2) * 8 - 5);
  const SORT_2 msb_SORT_2 = (SORT_2)1 << (5 - 1);
  typedef unsigned short SORT_3;  // BV with 16 bits
  const SORT_3 mask_SORT_3 = (SORT_3)-1 >> (sizeof(SORT_3) * 8 - 16);
  const SORT_3 msb_SORT_3 = (SORT_3)1 << (16 - 1);
  typedef unsigned int SORT_4;  // BV with 32 bits
  const SORT_4 mask_SORT_4 = (SORT_4)-1 >> (sizeof(SORT_4) * 8 - 32);
  const SORT_4 msb_SORT_4 = (SORT_4)1 << (32 - 1);
  // Initializing constants ...
  const SORT_3 var_5 = 0;
  const SORT_1 var_12 = 0;
  const SORT_3 var_34 = 1;
  const SORT_3 var_37 = 0;
  const SORT_1 var_62 = 1;
  const SORT_4 var_65 = 20;
  const SORT_3 var_66 = 0;
  const SORT_4 var_68 = 16;
  const SORT_4 var_171 = 17;
  // Collecting input declarations ...
  SORT_3 input_44;
  SORT_3 input_46;
  SORT_3 input_48;
  SORT_1 input_50;
  SORT_1 input_52;
  SORT_1 input_54;
  SORT_1 input_56;
  SORT_1 input_58;
  SORT_1 input_60;
  SORT_1 input_64;
  SORT_1 input_74;
  SORT_1 input_78;
  SORT_1 input_81;
  SORT_1 input_96;
  SORT_1 input_100;
  // Collecting state declarations ...
  SORT_3 state_6 = __VERIFIER_nondet_ushort() & mask_SORT_3;
  SORT_3 state_8 = __VERIFIER_nondet_ushort() & mask_SORT_3;
  SORT_3 state_10 = __VERIFIER_nondet_ushort() & mask_SORT_3;
  SORT_1 state_13 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_15 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_17 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_19 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_21 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_23 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_25 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  SORT_1 state_27 = __VERIFIER_nondet_uchar() & mask_SORT_1;
  // Initializing states ...
  SORT_3 init_7_arg_1 = var_5;
  state_6 = init_7_arg_1;
  SORT_3 init_9_arg_1 = var_5;
  state_8 = init_9_arg_1;
  SORT_3 init_11_arg_1 = var_5;
  state_10 = init_11_arg_1;
  SORT_1 init_14_arg_1 = var_12;
  state_13 = init_14_arg_1;
  SORT_1 init_16_arg_1 = var_12;
  state_15 = init_16_arg_1;
  SORT_1 init_18_arg_1 = var_12;
  state_17 = init_18_arg_1;
  SORT_1 init_20_arg_1 = var_12;
  state_19 = init_20_arg_1;
  SORT_1 init_22_arg_1 = var_12;
  state_21 = init_22_arg_1;
  SORT_1 init_24_arg_1 = var_12;
  state_23 = init_24_arg_1;
  SORT_1 init_26_arg_1 = var_12;
  state_25 = init_26_arg_1;
  SORT_1 init_28_arg_1 = var_12;
  state_27 = init_28_arg_1;
  for (;;) {
    // Getting external input values ...
    input_44 = __VERIFIER_nondet_ushort();
    input_44 = input_44 & mask_SORT_3;
    input_46 = __VERIFIER_nondet_ushort();
    input_46 = input_46 & mask_SORT_3;
    input_48 = __VERIFIER_nondet_ushort();
    input_48 = input_48 & mask_SORT_3;
    input_50 = __VERIFIER_nondet_uchar();
    input_50 = input_50 & mask_SORT_1;
    input_52 = __VERIFIER_nondet_uchar();
    input_52 = input_52 & mask_SORT_1;
    input_54 = __VERIFIER_nondet_uchar();
    input_54 = input_54 & mask_SORT_1;
    input_56 = __VERIFIER_nondet_uchar();
    input_56 = input_56 & mask_SORT_1;
    input_58 = __VERIFIER_nondet_uchar();
    input_58 = input_58 & mask_SORT_1;
    input_60 = __VERIFIER_nondet_uchar();
    input_60 = input_60 & mask_SORT_1;
    input_64 = __VERIFIER_nondet_uchar();
    input_64 = input_64 & mask_SORT_1;
    input_74 = __VERIFIER_nondet_uchar();
    input_74 = input_74 & mask_SORT_1;
    input_78 = __VERIFIER_nondet_uchar();
    input_78 = input_78 & mask_SORT_1;
    input_81 = __VERIFIER_nondet_uchar();
    input_81 = input_81 & mask_SORT_1;
    input_96 = __VERIFIER_nondet_uchar();
    input_96 = input_96 & mask_SORT_1;
    input_100 = __VERIFIER_nondet_uchar();
    input_100 = input_100 & mask_SORT_1;
    // Assuming invariants ...
    // Asserting properties ...
    SORT_1 var_29_arg_0 = state_13;
    SORT_1 var_29_arg_1 = ~state_15;
    var_29_arg_1 = var_29_arg_1 & mask_SORT_1;
    SORT_1 var_29 = var_29_arg_0 & var_29_arg_1;
    SORT_1 var_30_arg_0 = var_29;
    SORT_1 var_30_arg_1 = ~state_17;
    var_30_arg_1 = var_30_arg_1 & mask_SORT_1;
    SORT_1 var_30 = var_30_arg_0 & var_30_arg_1;
    SORT_1 var_31_arg_0 = var_30;
    SORT_1 var_31_arg_1 = state_19;
    SORT_1 var_31 = var_31_arg_0 & var_31_arg_1;
    SORT_1 var_32_arg_0 = var_31;
    SORT_1 var_32_arg_1 = ~state_21;
    var_32_arg_1 = var_32_arg_1 & mask_SORT_1;
    SORT_1 var_32 = var_32_arg_0 & var_32_arg_1;
    SORT_1 var_33_arg_0 = var_32;
    SORT_1 var_33_arg_1 = ~state_23;
    var_33_arg_1 = var_33_arg_1 & mask_SORT_1;
    SORT_1 var_33 = var_33_arg_0 & var_33_arg_1;
    SORT_3 var_35_arg_0 = var_34;
    SORT_3 var_35_arg_1 = state_6;
    SORT_1 var_35 = var_35_arg_0 == var_35_arg_1;
    SORT_1 var_36_arg_0 = var_33;
    SORT_1 var_36_arg_1 = var_35;
    SORT_1 var_36 = var_36_arg_0 & var_36_arg_1;
    SORT_3 var_38_arg_0 = var_37;
    SORT_3 var_38_arg_1 = state_8;
    SORT_1 var_38 = var_38_arg_0 == var_38_arg_1;
    SORT_1 var_39_arg_0 = var_36;
    SORT_1 var_39_arg_1 = var_38;
    SORT_1 var_39 = var_39_arg_0 & var_39_arg_1;
    SORT_3 var_40_arg_0 = var_37;
    SORT_3 var_40_arg_1 = state_10;
    SORT_1 var_40 = var_40_arg_0 == var_40_arg_1;
    SORT_1 var_41_arg_0 = var_39;
    SORT_1 var_41_arg_1 = var_40;
    SORT_1 var_41 = var_41_arg_0 & var_41_arg_1;
    SORT_1 var_42_arg_0 = state_27;
    SORT_1 var_42_arg_1 = var_41;
    SORT_1 var_42 = var_42_arg_0 & var_42_arg_1;
    var_42 = var_42 & mask_SORT_1;
    SORT_1 bad_43_arg_0 = var_42;
    __VERIFIER_assert(!(bad_43_arg_0));
    // Computing next states ...
    SORT_3 next_45_arg_1 = input_44;
    SORT_3 next_47_arg_1 = input_46;
    SORT_3 next_49_arg_1 = input_48;
    SORT_1 next_51_arg_1 = input_50;
    SORT_1 next_53_arg_1 = input_52;
    SORT_1 next_55_arg_1 = input_54;
    SORT_1 next_57_arg_1 = input_56;
    SORT_1 next_59_arg_1 = input_58;
    SORT_1 next_61_arg_1 = input_60;
    SORT_1 next_63_arg_1 = var_62;
    SORT_3 var_67_arg_0 = input_44;
    SORT_3 var_67_arg_1 = var_66;
    SORT_4 var_67 = ((SORT_4)var_67_arg_0 << 16) | var_67_arg_1;
    SORT_4 var_69_arg_0 = var_67;
    var_69_arg_0 = (var_69_arg_0 & msb_SORT_4) ? (var_69_arg_0 | ~mask_SORT_4) : (var_69_arg_0 & mask_SORT_4);
    SORT_4 var_69_arg_1 = var_68;
    SORT_4 var_69 = (int)var_69_arg_0 >> var_69_arg_1;
    var_69 = (var_69_arg_0 & msb_SORT_4) ? (var_69 | ~(mask_SORT_4 >> var_69_arg_1)) : var_69;
    var_69 = var_69 & mask_SORT_4;
    SORT_4 var_70_arg_0 = var_65;
    SORT_4 var_70_arg_1 = var_69;
    SORT_1 var_70 = var_70_arg_0 <= var_70_arg_1;
    SORT_1 var_71_arg_0 = input_50;
    SORT_1 var_71_arg_1 = ~var_70;
    var_71_arg_1 = var_71_arg_1 & mask_SORT_1;
    SORT_1 var_71 = var_71_arg_0 & var_71_arg_1;
    SORT_1 var_72_arg_0 = ~input_64;
    var_72_arg_0 = var_72_arg_0 & mask_SORT_1;
    SORT_1 var_72_arg_1 = var_71;
    SORT_1 var_72 = var_72_arg_0 | var_72_arg_1;
    SORT_1 var_73_arg_0 = input_52;
    SORT_1 var_73_arg_1 = input_64;
    SORT_1 var_73 = var_73_arg_0 | var_73_arg_1;
    SORT_1 var_75_arg_0 = var_73;
    SORT_1 var_75_arg_1 = ~input_74;
    var_75_arg_1 = var_75_arg_1 & mask_SORT_1;
    SORT_1 var_75 = var_75_arg_0 | var_75_arg_1;
    SORT_1 var_76_arg_0 = var_72;
    SORT_1 var_76_arg_1 = var_75;
    SORT_1 var_76 = var_76_arg_0 & var_76_arg_1;
    SORT_1 var_77_arg_0 = input_54;
    SORT_1 var_77_arg_1 = input_74;
    SORT_1 var_77 = var_77_arg_0 | var_77_arg_1;
    SORT_1 var_79_arg_0 = var_77;
    SORT_1 var_79_arg_1 = ~input_78;
    var_79_arg_1 = var_79_arg_1 & mask_SORT_1;
    SORT_1 var_79 = var_79_arg_0 | var_79_arg_1;
    SORT_1 var_80_arg_0 = var_76;
    SORT_1 var_80_arg_1 = var_79;
    SORT_1 var_80 = var_80_arg_0 & var_80_arg_1;
    SORT_1 var_82_arg_0 = input_64;
    SORT_3 var_82_arg_1 = input_44;
    SORT_3 var_82_arg_2 = input_46;
    SORT_3 var_82 = var_82_arg_0 ? var_82_arg_1 : var_82_arg_2;
    SORT_3 var_83_arg_0 = var_82;
    SORT_3 var_83_arg_1 = var_66;
    SORT_4 var_83 = ((SORT_4)var_83_arg_0 << 16) | var_83_arg_1;
    SORT_4 var_84_arg_0 = var_83;
    var_84_arg_0 = (var_84_arg_0 & msb_SORT_4) ? (var_84_arg_0 | ~mask_SORT_4) : (var_84_arg_0 & mask_SORT_4);
    SORT_4 var_84_arg_1 = var_68;
    SORT_4 var_84 = (int)var_84_arg_0 >> var_84_arg_1;
    var_84 = (var_84_arg_0 & msb_SORT_4) ? (var_84 | ~(mask_SORT_4 >> var_84_arg_1)) : var_84;
    SORT_4 var_85_arg_0 = var_69;
    SORT_4 var_85_arg_1 = var_84;
    SORT_4 var_85 = var_85_arg_0 + var_85_arg_1;
    SORT_4 var_86_arg_0 = var_85;
    SORT_3 var_86 = var_86_arg_0 >> 0;
    SORT_1 var_87_arg_0 = input_74;
    SORT_3 var_87_arg_1 = var_86;
    SORT_3 var_87_arg_2 = var_82;
    SORT_3 var_87 = var_87_arg_0 ? var_87_arg_1 : var_87_arg_2;
    var_87 = var_87 & mask_SORT_3;
    SORT_1 var_88_arg_0 = input_78;
    SORT_3 var_88_arg_1 = var_87;
    SORT_3 var_88_arg_2 = input_44;
    SORT_3 var_88 = var_88_arg_0 ? var_88_arg_1 : var_88_arg_2;
    SORT_3 var_89_arg_0 = var_88;
    SORT_3 var_89_arg_1 = var_66;
    SORT_4 var_89 = ((SORT_4)var_89_arg_0 << 16) | var_89_arg_1;
    SORT_4 var_90_arg_0 = var_89;
    var_90_arg_0 = (var_90_arg_0 & msb_SORT_4) ? (var_90_arg_0 | ~mask_SORT_4) : (var_90_arg_0 & mask_SORT_4);
    SORT_4 var_90_arg_1 = var_68;
    SORT_4 var_90 = (int)var_90_arg_0 >> var_90_arg_1;
    var_90 = (var_90_arg_0 & msb_SORT_4) ? (var_90 | ~(mask_SORT_4 >> var_90_arg_1)) : var_90;
    var_90 = var_90 & mask_SORT_4;
    SORT_4 var_91_arg_0 = var_65;
    SORT_4 var_91_arg_1 = var_90;
    SORT_1 var_91 = var_91_arg_0 <= var_91_arg_1;
    SORT_1 var_92_arg_0 = input_56;
    SORT_1 var_92_arg_1 = ~var_91;
    var_92_arg_1 = var_92_arg_1 & mask_SORT_1;
    SORT_1 var_92 = var_92_arg_0 & var_92_arg_1;
    SORT_1 var_93_arg_0 = ~input_81;
    var_93_arg_0 = var_93_arg_0 & mask_SORT_1;
    SORT_1 var_93_arg_1 = var_92;
    SORT_1 var_93 = var_93_arg_0 | var_93_arg_1;
    SORT_1 var_94_arg_0 = var_80;
    SORT_1 var_94_arg_1 = var_93;
    SORT_1 var_94 = var_94_arg_0 & var_94_arg_1;
    SORT_1 var_95_arg_0 = input_58;
    SORT_1 var_95_arg_1 = input_81;
    SORT_1 var_95 = var_95_arg_0 | var_95_arg_1;
    SORT_1 var_97_arg_0 = var_95;
    SORT_1 var_97_arg_1 = ~input_96;
    var_97_arg_1 = var_97_arg_1 & mask_SORT_1;
    SORT_1 var_97 = var_97_arg_0 | var_97_arg_1;
    SORT_1 var_98_arg_0 = var_94;
    SORT_1 var_98_arg_1 = var_97;
    SORT_1 var_98 = var_98_arg_0 & var_98_arg_1;
    SORT_1 var_99_arg_0 = input_60;
    SORT_1 var_99_arg_1 = input_96;
    SORT_1 var_99 = var_99_arg_0 | var_99_arg_1;
    SORT_1 var_101_arg_0 = var_99;
    SORT_1 var_101_arg_1 = ~input_100;
    var_101_arg_1 = var_101_arg_1 & mask_SORT_1;
    SORT_1 var_101 = var_101_arg_0 | var_101_arg_1;
    SORT_1 var_102_arg_0 = var_98;
    SORT_1 var_102_arg_1 = var_101;
    SORT_1 var_102 = var_102_arg_0 & var_102_arg_1;
    SORT_1 var_103_arg_0 = input_64;
    SORT_1 var_103_arg_1 = input_74;
    SORT_1 var_103 = var_103_arg_0 | var_103_arg_1;
    SORT_1 var_104_arg_0 = input_78;
    SORT_1 var_104_arg_1 = var_103;
    SORT_1 var_104 = var_104_arg_0 | var_104_arg_1;
    SORT_1 var_105_arg_0 = input_81;
    SORT_1 var_105_arg_1 = var_104;
    SORT_1 var_105 = var_105_arg_0 | var_105_arg_1;
    SORT_1 var_106_arg_0 = input_96;
    SORT_1 var_106_arg_1 = var_105;
    SORT_1 var_106 = var_106_arg_0 | var_106_arg_1;
    SORT_1 var_107_arg_0 = input_100;
    SORT_1 var_107_arg_1 = var_106;
    SORT_1 var_107 = var_107_arg_0 | var_107_arg_1;
    SORT_1 var_108_arg_0 = var_102;
    SORT_1 var_108_arg_1 = var_107;
    SORT_1 var_108 = var_108_arg_0 & var_108_arg_1;
    SORT_1 var_109_arg_0 = input_50;
    SORT_1 var_109_arg_1 = input_52;
    SORT_1 var_109 = var_109_arg_0 & var_109_arg_1;
    SORT_1 var_110_arg_0 = input_50;
    SORT_1 var_110_arg_1 = input_52;
    SORT_1 var_110 = var_110_arg_0 | var_110_arg_1;
    SORT_1 var_111_arg_0 = input_54;
    SORT_1 var_111_arg_1 = var_110;
    SORT_1 var_111 = var_111_arg_0 & var_111_arg_1;
    SORT_1 var_112_arg_0 = var_109;
    SORT_1 var_112_arg_1 = var_111;
    SORT_1 var_112 = var_112_arg_0 | var_112_arg_1;
    SORT_1 var_113_arg_0 = input_54;
    SORT_1 var_113_arg_1 = var_110;
    SORT_1 var_113 = var_113_arg_0 | var_113_arg_1;
    SORT_1 var_114_arg_0 = ~var_112;
    var_114_arg_0 = var_114_arg_0 & mask_SORT_1;
    SORT_1 var_114_arg_1 = var_113;
    SORT_1 var_114 = var_114_arg_0 & var_114_arg_1;
    SORT_1 var_115_arg_0 = input_56;
    SORT_1 var_115_arg_1 = input_58;
    SORT_1 var_115 = var_115_arg_0 & var_115_arg_1;
    SORT_1 var_116_arg_0 = input_56;
    SORT_1 var_116_arg_1 = input_58;
    SORT_1 var_116 = var_116_arg_0 | var_116_arg_1;
    SORT_1 var_117_arg_0 = input_60;
    SORT_1 var_117_arg_1 = var_116;
    SORT_1 var_117 = var_117_arg_0 & var_117_arg_1;
    SORT_1 var_118_arg_0 = var_115;
    SORT_1 var_118_arg_1 = var_117;
    SORT_1 var_118 = var_118_arg_0 | var_118_arg_1;
    SORT_1 var_119_arg_0 = var_114;
    SORT_1 var_119_arg_1 = ~var_118;
    var_119_arg_1 = var_119_arg_1 & mask_SORT_1;
    SORT_1 var_119 = var_119_arg_0 & var_119_arg_1;
    SORT_1 var_120_arg_0 = input_60;
    SORT_1 var_120_arg_1 = var_116;
    SORT_1 var_120 = var_120_arg_0 | var_120_arg_1;
    SORT_1 var_121_arg_0 = var_119;
    SORT_1 var_121_arg_1 = var_120;
    SORT_1 var_121 = var_121_arg_0 & var_121_arg_1;
    SORT_1 var_122_arg_0 = var_108;
    SORT_1 var_122_arg_1 = var_121;
    SORT_1 var_122 = var_122_arg_0 & var_122_arg_1;
    SORT_1 var_123_arg_0 = var_73;
    SORT_1 var_123_arg_1 = ~input_74;
    var_123_arg_1 = var_123_arg_1 & mask_SORT_1;
    SORT_1 var_123 = var_123_arg_0 & var_123_arg_1;
    var_123 = var_123 & mask_SORT_1;
    SORT_1 var_124_arg_0 = input_50;
    SORT_1 var_124_arg_1 = ~input_64;
    var_124_arg_1 = var_124_arg_1 & mask_SORT_1;
    SORT_1 var_124 = var_124_arg_0 & var_124_arg_1;
    SORT_1 var_125_arg_0 = var_124;
    SORT_1 var_125_arg_1 = input_78;
    SORT_1 var_125 = var_125_arg_0 | var_125_arg_1;
    var_125 = var_125 & mask_SORT_1;
    SORT_1 var_126_arg_0 = var_123;
    SORT_1 var_126_arg_1 = var_125;
    SORT_1 var_126 = var_126_arg_0 & var_126_arg_1;
    SORT_1 var_127_arg_0 = var_77;
    SORT_1 var_127_arg_1 = ~input_78;
    var_127_arg_1 = var_127_arg_1 & mask_SORT_1;
    SORT_1 var_127 = var_127_arg_0 & var_127_arg_1;
    var_127 = var_127 & mask_SORT_1;
    SORT_1 var_128_arg_0 = var_123;
    SORT_1 var_128_arg_1 = var_125;
    SORT_1 var_128 = var_128_arg_0 | var_128_arg_1;
    SORT_1 var_129_arg_0 = var_127;
    SORT_1 var_129_arg_1 = var_128;
    SORT_1 var_129 = var_129_arg_0 & var_129_arg_1;
    SORT_1 var_130_arg_0 = var_126;
    SORT_1 var_130_arg_1 = var_129;
    SORT_1 var_130 = var_130_arg_0 | var_130_arg_1;
    SORT_1 var_131_arg_0 = var_127;
    SORT_1 var_131_arg_1 = var_128;
    SORT_1 var_131 = var_131_arg_0 | var_131_arg_1;
    SORT_1 var_132_arg_0 = ~var_130;
    var_132_arg_0 = var_132_arg_0 & mask_SORT_1;
    SORT_1 var_132_arg_1 = var_131;
    SORT_1 var_132 = var_132_arg_0 & var_132_arg_1;
    SORT_1 var_133_arg_0 = var_95;
    SORT_1 var_133_arg_1 = ~input_96;
    var_133_arg_1 = var_133_arg_1 & mask_SORT_1;
    SORT_1 var_133 = var_133_arg_0 & var_133_arg_1;
    var_133 = var_133 & mask_SORT_1;
    SORT_1 var_134_arg_0 = input_56;
    SORT_1 var_134_arg_1 = ~input_81;
    var_134_arg_1 = var_134_arg_1 & mask_SORT_1;
    SORT_1 var_134 = var_134_arg_0 & var_134_arg_1;
    SORT_1 var_135_arg_0 = var_134;
    SORT_1 var_135_arg_1 = input_100;
    SORT_1 var_135 = var_135_arg_0 | var_135_arg_1;
    var_135 = var_135 & mask_SORT_1;
    SORT_1 var_136_arg_0 = var_133;
    SORT_1 var_136_arg_1 = var_135;
    SORT_1 var_136 = var_136_arg_0 & var_136_arg_1;
    SORT_1 var_137_arg_0 = var_99;
    SORT_1 var_137_arg_1 = ~input_100;
    var_137_arg_1 = var_137_arg_1 & mask_SORT_1;
    SORT_1 var_137 = var_137_arg_0 & var_137_arg_1;
    var_137 = var_137 & mask_SORT_1;
    SORT_1 var_138_arg_0 = var_133;
    SORT_1 var_138_arg_1 = var_135;
    SORT_1 var_138 = var_138_arg_0 | var_138_arg_1;
    SORT_1 var_139_arg_0 = var_137;
    SORT_1 var_139_arg_1 = var_138;
    SORT_1 var_139 = var_139_arg_0 & var_139_arg_1;
    SORT_1 var_140_arg_0 = var_136;
    SORT_1 var_140_arg_1 = var_139;
    SORT_1 var_140 = var_140_arg_0 | var_140_arg_1;
    SORT_1 var_141_arg_0 = var_132;
    SORT_1 var_141_arg_1 = ~var_140;
    var_141_arg_1 = var_141_arg_1 & mask_SORT_1;
    SORT_1 var_141 = var_141_arg_0 & var_141_arg_1;
    SORT_1 var_142_arg_0 = var_137;
    SORT_1 var_142_arg_1 = var_138;
    SORT_1 var_142 = var_142_arg_0 | var_142_arg_1;
    SORT_1 var_143_arg_0 = var_141;
    SORT_1 var_143_arg_1 = var_142;
    SORT_1 var_143 = var_143_arg_0 & var_143_arg_1;
    SORT_1 var_144_arg_0 = var_122;
    SORT_1 var_144_arg_1 = var_143;
    SORT_1 var_144 = var_144_arg_0 & var_144_arg_1;
    SORT_1 var_145_arg_0 = input_81;
    SORT_3 var_145_arg_1 = var_88;
    SORT_3 var_145_arg_2 = input_48;
    SORT_3 var_145 = var_145_arg_0 ? var_145_arg_1 : var_145_arg_2;
    SORT_3 var_146_arg_0 = var_145;
    SORT_3 var_146_arg_1 = var_66;
    SORT_4 var_146 = ((SORT_4)var_146_arg_0 << 16) | var_146_arg_1;
    SORT_4 var_147_arg_0 = var_146;
    var_147_arg_0 = (var_147_arg_0 & msb_SORT_4) ? (var_147_arg_0 | ~mask_SORT_4) : (var_147_arg_0 & mask_SORT_4);
    SORT_4 var_147_arg_1 = var_68;
    SORT_4 var_147 = (int)var_147_arg_0 >> var_147_arg_1;
    var_147 = (var_147_arg_0 & msb_SORT_4) ? (var_147 | ~(mask_SORT_4 >> var_147_arg_1)) : var_147;
    SORT_4 var_148_arg_0 = var_90;
    SORT_4 var_148_arg_1 = var_147;
    SORT_4 var_148 = var_148_arg_0 + var_148_arg_1;
    SORT_4 var_149_arg_0 = var_148;
    SORT_3 var_149 = var_149_arg_0 >> 0;
    SORT_1 var_150_arg_0 = input_96;
    SORT_3 var_150_arg_1 = var_149;
    SORT_3 var_150_arg_2 = var_145;
    SORT_3 var_150 = var_150_arg_0 ? var_150_arg_1 : var_150_arg_2;
    var_150 = var_150 & mask_SORT_3;
    SORT_1 var_151_arg_0 = input_100;
    SORT_3 var_151_arg_1 = var_150;
    SORT_3 var_151_arg_2 = var_88;
    SORT_3 var_151 = var_151_arg_0 ? var_151_arg_1 : var_151_arg_2;
    var_151 = var_151 & mask_SORT_3;
    SORT_3 var_152_arg_0 = var_151;
    SORT_3 var_152_arg_1 = state_6;
    SORT_1 var_152 = var_152_arg_0 == var_152_arg_1;
    SORT_1 var_153_arg_0 = var_144;
    SORT_1 var_153_arg_1 = var_152;
    SORT_1 var_153 = var_153_arg_0 & var_153_arg_1;
    SORT_3 var_154_arg_0 = var_87;
    SORT_3 var_154_arg_1 = state_8;
    SORT_1 var_154 = var_154_arg_0 == var_154_arg_1;
    SORT_1 var_155_arg_0 = var_153;
    SORT_1 var_155_arg_1 = var_154;
    SORT_1 var_155 = var_155_arg_0 & var_155_arg_1;
    SORT_3 var_156_arg_0 = var_150;
    SORT_3 var_156_arg_1 = state_10;
    SORT_1 var_156 = var_156_arg_0 == var_156_arg_1;
    SORT_1 var_157_arg_0 = var_155;
    SORT_1 var_157_arg_1 = var_156;
    SORT_1 var_157 = var_157_arg_0 & var_157_arg_1;
    SORT_1 var_158_arg_0 = var_125;
    SORT_1 var_158_arg_1 = state_13;
    SORT_1 var_158 = var_158_arg_0 == var_158_arg_1;
    SORT_1 var_159_arg_0 = var_157;
    SORT_1 var_159_arg_1 = var_158;
    SORT_1 var_159 = var_159_arg_0 & var_159_arg_1;
    SORT_1 var_160_arg_0 = var_123;
    SORT_1 var_160_arg_1 = state_15;
    SORT_1 var_160 = var_160_arg_0 == var_160_arg_1;
    SORT_1 var_161_arg_0 = var_159;
    SORT_1 var_161_arg_1 = var_160;
    SORT_1 var_161 = var_161_arg_0 & var_161_arg_1;
    SORT_1 var_162_arg_0 = var_127;
    SORT_1 var_162_arg_1 = state_17;
    SORT_1 var_162 = var_162_arg_0 == var_162_arg_1;
    SORT_1 var_163_arg_0 = var_161;
    SORT_1 var_163_arg_1 = var_162;
    SORT_1 var_163 = var_163_arg_0 & var_163_arg_1;
    SORT_1 var_164_arg_0 = var_135;
    SORT_1 var_164_arg_1 = state_19;
    SORT_1 var_164 = var_164_arg_0 == var_164_arg_1;
    SORT_1 var_165_arg_0 = var_163;
    SORT_1 var_165_arg_1 = var_164;
    SORT_1 var_165 = var_165_arg_0 & var_165_arg_1;
    SORT_1 var_166_arg_0 = var_133;
    SORT_1 var_166_arg_1 = state_21;
    SORT_1 var_166 = var_166_arg_0 == var_166_arg_1;
    SORT_1 var_167_arg_0 = var_165;
    SORT_1 var_167_arg_1 = var_166;
    SORT_1 var_167 = var_167_arg_0 & var_167_arg_1;
    SORT_1 var_168_arg_0 = var_137;
    SORT_1 var_168_arg_1 = state_23;
    SORT_1 var_168 = var_168_arg_0 == var_168_arg_1;
    SORT_1 var_169_arg_0 = var_167;
    SORT_1 var_169_arg_1 = var_168;
    SORT_1 var_169 = var_169_arg_0 & var_169_arg_1;
    SORT_1 var_170_arg_0 = var_169;
    SORT_1 var_170_arg_1 = state_27;
    SORT_1 var_170 = var_170_arg_0 & var_170_arg_1;
    SORT_4 var_172_arg_0 = var_171;
    SORT_4 var_172_arg_1 = var_69;
    SORT_1 var_172 = var_172_arg_0 == var_172_arg_1;
    SORT_1 var_173_arg_0 = state_25;
    SORT_1 var_173_arg_1 = var_170;
    SORT_1 var_173_arg_2 = var_172;
    SORT_1 var_173 = var_173_arg_0 ? var_173_arg_1 : var_173_arg_2;
    SORT_1 next_174_arg_1 = var_173;
    // Assigning next states ...
    state_6 = next_45_arg_1;
    state_8 = next_47_arg_1;
    state_10 = next_49_arg_1;
    state_13 = next_51_arg_1;
    state_15 = next_53_arg_1;
    state_17 = next_55_arg_1;
    state_19 = next_57_arg_1;
    state_21 = next_59_arg_1;
    state_23 = next_61_arg_1;
    state_25 = next_63_arg_1;
    state_27 = next_174_arg_1;
  }
  return 0;
}