#!/bin/bash
###############
# DIRECTORIES #
###############
BASEDIR=$(shell pwd)

############
# COMMANDS #
############
cd ${BASEDIR} && make 1>/dev/null
z3 -smt2 ${BASEDIR}/FOLDER_6_OUTPUT/Output.txt > /home/oren/output.txt
