/* -*- C -*- */
/* _-_ This contains info generated by getSymbolicSolution */
/* _-_ in order to generate tests. */
#include "stdint.h"
#include "stddef.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Index of ConcretizedObject in array */
typedef struct Offset Offset;
struct Offset {
  unsigned offset;
  uintptr_t index;
};

typedef struct ConcretizedObject ConcretizedObject;
struct ConcretizedObject {
  char* name;
  unsigned char* values;
  unsigned size;
  /* offset - child id */
  Offset* offsets;
  size_t n_offsets;
};

typedef struct TestCase TestCase;
struct TestCase {
  ConcretizedObject* objects;
  size_t n_objects;

  unsigned numArgs;
  char **args;
  unsigned symArgvs;
  unsigned symArgvLen;
};

TestCase* TC_fromFile(const char *path);
  
#ifdef __cplusplus
}
#endif
