task:
  freebsd_instance:
    matrix:
      - image: freebsd-11-3-stable-amd64-v20190801
      - image: freebsd-12-0-release-amd64
  deps_script:
    - sed -i.bak -e 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
    - env ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y llvm80 gmake z3 cmake pkgconf google-perftools python3 python37 py37-sqlite3 py37-tabulate
  build_script:
    - mkdir build
    - cd build
    - cmake -DLLVM_CONFIG_BINARY=/usr/local/bin/llvm-config80 -DMAKE_BINARY=/usr/local/bin/gmake -DENABLE_TCMALLOC:BOOL=true -DENABLE_POSIX_RUNTIME:BOOL=ON -DENABLE_SOLVER_Z3:BOOL=true -DENABLE_SYSTEM_TESTS:BOOL=ON ..
    - gmake
  test_script:
    - sed -i.bak -e 's/lit\./lit80\./' test/lit.cfg
    - cd build
    - gmake check
