codecov:
  disable_default_path_fixes: true

coverage:
  range: 70...90
  precision: 2
  round: down
  status:
    project: no
    patch: yes
    changes: no

fixes:
  - "/tmp/klee_src::"

ignore:
  - "test/"
  - "unittests"
  - "**/test-utils"

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default
