; RUN: rm -rf %T/xxx
;
; The output directory must be explicitly set so that it ends up in the Output/
; directory which is not scanned for .ll files by llvm-lit, otherwise running
; test suite a second time will cause problems because assembly.ll generated by
; executing this test case the first time will be detected as a test case.
;
; RUN: llvm-as -f %s -o - | %klee --output-dir=%T/xxx
; RUN: not test -f %T/xxx/klee-last/test0001.abort.err

declare void @klee_abort()

define i32 @foo(i8 signext %val) {
        %tmp = zext i8 %val to i32
	ret i32 %tmp
}

define i32 @main() {
	%res = call i32 bitcast (i32 (i8)* @foo to i32 (i1)*)( i1 1 )
        %check = icmp ne i32 %res, 255
        br i1 %check, label %error, label %exit

error:
        call void @klee_abort()
        unreachable

exit:
	ret i32 0
}
