#===-- stp/Makefile ----------------------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

LEVEL=..

PARALLEL_DIRS := AST bitvec c_interface constantbv sat simplifier

include $(LEVEL)/Makefile.common
