{
 "title": "Klee dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Instructions Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Instructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Instructions Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "Instructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Full Branches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "FullBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "FullBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Covered Instructions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "CoveredInstructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Covered Instructions Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 15, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "CoveredInstructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Malloc Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "MallocUsage", "type": "timeserie" }
   ]
  },
  {
   "title": "Malloc Usage Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 20 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "target": "MallocUsage", "type": "timeserie" }
   ]
  },
  {
   "title": "Partial Branches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "PartialBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Partial Branches Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "PartialBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Uncovered Instructions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "UncoveredInstructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Uncovered Instructions Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "UncoveredInstructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Solver Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "SolverTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Solver Time Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 41 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "SolverTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Branches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Branches Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 49 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "NumBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Num States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumStates", "type": "timeserie" }
   ]
  },
  {
   "title": "Num States Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "NumStates", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumQueries", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Queries Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 63 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "NumQueries", "type": "timeserie" }
   ]
  },
  {
   "title": "NumQueryConstructs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumQueryConstructs", "type": "timeserie" }
   ]
  },
  {
   "title": "NumQueryConstructs Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 71 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "NumQueryConstructs", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumObjects", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Objects Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 79 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "NumObjects", "type": "timeserie" }
   ]
  },
  {
   "title": "QueryCexCacheMisses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "QueryCexCacheMisses", "type": "timeserie" }
   ]
  },
  {
   "title": "QueryCexCacheMisses Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 87 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "QueryCexCacheMisses", "type": "timeserie" }
   ]
  },
  {
   "title": "Resolve Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ResolveTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Fork Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ForkTime", "type": "timeserie" }
   ]
  },
  {
   "title": "CexCache TIme",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "CexCacheTime", "type": "timeserie" }
   ]
  },
  {
   "title": "WallTime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "WallTime", "type": "timeserie" }
   ]
  },
  {
   "title": "QueryTime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "QueryTime", "type": "timeserie" }
   ]
  },
  {
   "title": "UserTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "UserTime", "type": "timeserie" }
   ]
  }
 ]
}