{
 "title": "KLEE",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Instructions Processed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "Instructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Instructions Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Instructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Full Branches",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "FullBranches", "type": "table" }
   ]
  },
  {
   "title": "Full Branches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "FullBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Covered Instructions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "CoveredInstructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Covered Instructions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "CoveredInstructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Malloc Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 20 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "target": "MallocUsage", "type": "timeserie" }
   ]
  },
  {
   "title": "Malloc Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "MallocUsage", "type": "timeserie" }
   ]
  },
  {
   "title": "Partial Branches ",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 27 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "PartialBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Partial Branches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "PartialBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Uncovered Instructions ",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 34 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "UncoveredInstructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Uncovered Instructions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "UncoveredInstructions", "type": "timeserie" }
   ]
  },
  {
   "title": "Solver Time ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "SolverTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Solver Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 7, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "SolverTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Branches",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 49 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "NumBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Branches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumBranches", "type": "timeserie" }
   ]
  },
  {
   "title": "Num States",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 56 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "NumStates", "type": "timeserie" }
   ]
  },
  {
   "title": "Num States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumStates", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Queries",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 63 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "NumQueries", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 7, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumQueries", "type": "timeserie" }
   ]
  },
  {
   "title": "NumQueryConstructs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 71 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "NumQueryConstructs", "type": "timeserie" }
   ]
  },
  {
   "title": "NumQueryConstructs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 7, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumQueryConstructs", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Objects ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 79 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "NumObjects", "type": "timeserie" }
   ]
  },
  {
   "title": "Num Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 7, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "NumObjects", "type": "timeserie" }
   ]
  },
  {
   "title": "QueryCexCacheMisses Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 87 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "target": "QueryCexCacheMisses", "type": "timeserie" }
   ]
  },
  {
   "title": "QueryCexCacheMisses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 7, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "QueryCexCacheMisses", "type": "timeserie" }
   ]
  },
  {
   "title": "Resolve Time",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 95 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "ResolveTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Resolve Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 7, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ResolveTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Fork Time",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 103 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "ForkTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Fork Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 7, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "ForkTime", "type": "timeserie" }
   ]
  },
  {
   "title": "CexCache Time ",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 111 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "CexCacheTime", "type": "timeserie" }
   ]
  },
  {
   "title": "CexCache TIme",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "CexCacheTime", "type": "timeserie" }
   ]
  },
  {
   "title": "Wall Time ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 118 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    { "target": "WallTime", "type": "timeserie" }
   ]
  },
  {
   "title": "WallTime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 7, "y": 118 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "target": "WallTime", "type": "timeserie" }
   ]
  },
  {
   "title": "QueryTime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 126 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "QueryTime", "type": "timeserie" }
   ]
  },
  {
   "title": "QueryTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "QueryTime", "type": "timeserie" }
   ]
  },
  {
   "title": "UserTime ",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 133 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    { "target": "UserTime", "type": "timeserie" }
   ]
  },
  {
   "title": "UserTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 7, "y": 133 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "target": "UserTime", "type": "timeserie" }
   ]
  }
 ]
}