##===- unittests/Expr/Makefile -----------------------------*- Makefile -*-===##

LEVEL := ../..
include $(LEVEL)/Makefile.config

TESTNAME := TreeStreamTest
USEDLIBS := kleeBasic.a kleeSupport.a
LINK_COMPONENTS := support

include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest

