#===-- lib/Makefile ----------------------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

LEVEL=..

PARALLEL_DIRS=Basic Support Expr Solver Module Core

include $(LEVEL)/Makefile.common
