
gclang_config := 'CC=gclang CXX=gclang++ CFLAGS="-g -O0 -Xclang -disable-O0-optnone"'

gnumake version="4.4":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "gnumake" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/make/make-{{version}}.tar.gz
        tar zxf make-{{version}}.tar.gz
        mv make-{{version}} gnumake
        rm make-{{version}}.tar.gz
    fi
    pushd gnumake
        ./configure {{gclang_config}} --prefix=$PWD/install
        make -j $(nproc)
        make install
        get-bc $PWD/install/bin/make
    popd

lua version="5.4.8":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "lua" ]; then
        curl -fL -O https://www.lua.org/ftp/lua-{{version}}.tar.gz
        tar zxf lua-{{version}}.tar.gz
        mv lua-{{version}} lua
        rm lua-{{version}}.tar.gz
    fi
    pushd lua
        make clean
        make -j $(nproc) posix {{gclang_config}}
        make install INSTALL_TOP=$PWD/install
        get-bc $PWD/install/bin/lua
    popd
