
gclang_config := 'CC=gclang CXX=gclang++ CFLAGS="-g -O0 -Xclang -disable-O0-optnone"'

gnumake version="4.4":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "gnumake" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/make/make-{{version}}.tar.gz
        tar zxf make-{{version}}.tar.gz
        mv make-{{version}} gnumake
        rm make-{{version}}.tar.gz
    fi
    pushd gnumake
        ./configure {{gclang_config}} --prefix=$PWD/install
        make -j $(nproc)
        make install
        get-bc $PWD/install/bin/make
    popd

lua version="5.4.8":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "lua" ]; then
        curl -fL -O https://www.lua.org/ftp/lua-{{version}}.tar.gz
        tar zxf lua-{{version}}.tar.gz
        mv lua-{{version}} lua
        rm lua-{{version}}.tar.gz
    fi
    pushd lua
        make clean
        make -j $(nproc) posix {{gclang_config}}
        make install INSTALL_TOP=$PWD/install
        get-bc $PWD/install/bin/lua
    popd

openssl version="3.5.4":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "openssl" ]; then
        curl -fL -O https://github.com/openssl/openssl/releases/download/openssl-{{version}}/openssl-{{version}}.tar.gz
        tar zxf openssl-{{version}}.tar.gz
        mv openssl-{{version}} openssl
        rm openssl-{{version}}.tar.gz
    fi
    pushd openssl
        {{gclang_config}} ./Configure  --prefix=$PWD/install no-shared no-module enable-tls1_3 enable-rc5 enable-md2 enable-ec_nistp_64_gcc_128 enable-ssl3
        make -j $(nproc)
        make -j $(nproc) install
    popd

curl version="8.16.0":
    #!/usr/bin/env bash
    set -euxo pipefail
    install_dir=$PWD/curl/install
    src_dir=$PWD/curl/src
    if [ ! -d "$src_dir" ]; then
        mkdir -p $PWD/curl
        curl -fL -O https://curl.se/download/curl-{{version}}.tar.gz
        tar zxf curl-{{version}}.tar.gz
        mv curl-{{version}} $src_dir
        rm curl-{{version}}.tar.gz
    fi
    pushd $src_dir
        make clean
        {{gclang_config}} ./configure --prefix=$install_dir \
            --without-libpsl   \
            --without-librtmp  \
            --without-libgsasl \
            --without-ssl      \
            --without-zlib     \
            --without-brotli   \
            --without-zstd     \
            --disable-pthreads \
            --disable-rt       \
            --disable-shared
        make -j $(nproc)
        make -j $(nproc) install
    popd
    get-bc $install_dir/bin/curl


# bc (GNU bc)
bc version="1.07.1":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "bc-src" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/bc/bc-{{version}}.tar.gz
        tar zxf bc-{{version}}.tar.gz
        mv bc-{{version}} bc-src
        rm bc-{{version}}.tar.gz
    fi
    pushd bc-src
        {{gclang_config}}
        ./configure --prefix=$PWD/install --disable-shared
        make clean
        make -j $(nproc)
        make -j $(nproc) install
        get-bc "$PWD/install/bin/bc"
    popd

# tic (from ncurses)
tic version="6.4":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "ncurses" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/ncurses/ncurses-{{version}}.tar.gz
        tar zxf ncurses-{{version}}.tar.gz
        mv ncurses-{{version}} ncurses
        rm ncurses-{{version}}.tar.gz
    fi
    pushd ncurses
        {{gclang_config}} ./configure  --with-termlib --without-debug --prefix=$PWD/install
        make -j "$(nproc)"
        make install
        get-bc "$PWD/install/bin/tic"
    popd

bison version="3.8.2":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "bison" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/bison/bison-{{version}}.tar.gz
        tar zxf bison-{{version}}.tar.gz
        mv bison-{{version}} bison
        rm bison-{{version}}.tar.gz
    fi
    pushd bison
        {{gclang_config}} ./configure --prefix=$PWD/install
        make -j "$(nproc)"
        make install
        get-bc "$PWD/install/bin/bison"
    popd
  
# readelf and strip (from binutils)
binutils version="2.42":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "binutils" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/binutils/binutils-{{version}}.tar.xz
        tar Jxf binutils-{{version}}.tar.xz
        mv binutils-{{version}} binutils
        rm binutils-{{version}}.tar.xz
    fi
    pushd binutils
        {{gclang_config}}
        ./configure --disable-werror --prefix=$PWD/install
        make -j "$(nproc)"
        make install
        get-bc "$PWD/install/bin/readelf"
        get-bc "$PWD/install/bin/strip"
    popd

# ---- tiffinfo (from libtiff) ----
tiffinfo version="4.6.0":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "tiff" ]; then
        curl -fL -O https://download.osgeo.org/libtiff/tiff-{{version}}.tar.gz
        tar zxf tiff-{{version}}.tar.gz
        mv tiff-{{version}} tiff
        rm tiff-{{version}}.tar.gz
    fi
    pushd tiff
        make clean || true
        {{gclang_config}} ./configure --prefix="$PWD/install" --disable-shared
        make -j "$(nproc)"
        make install
        get-bc "$PWD/install/bin/tiffinfo"
    popd


# ---- flvmeta  ----
flvmeta version="1.2.2":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "flvmeta" ]; then
        curl -fL -o flvmeta-{{version}}.tar.gz \
          "https://github.com/noirotm/flvmeta/archive/refs/tags/v{{version}}.tar.gz"
        tar zxf flvmeta-{{version}}.tar.gz
        mv flvmeta-{{version}} flvmeta
        rm flvmeta-{{version}}.tar.gz
    fi
    pushd flvmeta
        rm -rf build
        {{gclang_config}} cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX="$PWD/install" \
            -DBUILD_SHARED_LIBS=OFF
        ninja -C build -j "$(nproc)"
        ninja -C build install
        get-bc "$PWD/install/bin/flvmeta"
    popd

# ---- transicc (from lcms2) ----
transicc version="2.16":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "lcms2" ]; then
        curl -fL -O https://downloads.sourceforge.net/project/lcms/lcms/{{version}}/lcms2-{{version}}.tar.gz
        tar zxf lcms2-{{version}}.tar.gz
        mv lcms2-{{version}} lcms2
        rm lcms2-{{version}}.tar.gz
    fi
    pushd lcms2
        make clean || true
        {{gclang_config}} ./configure --prefix="$PWD/install" --disable-shared
        make -j "$(nproc)"
        make install
        get-bc "$PWD/install/bin/transicc"
    popd


# ---- jasper  ----
jasper version="4.2.4":
    #!/usr/bin/env bash
    set -euxo pipefail

    # fresh, correct source (includes cmake/ modules)
    rm -rf jasper jasper-{{version}}.tar.gz
    curl -fL -o jasper-{{version}}.tar.gz \
      "https://github.com/jasper-software/jasper/releases/download/version-{{version}}/jasper-{{version}}.tar.gz"
    tar zxf jasper-{{version}}.tar.gz
    mv jasper-{{version}} jasper
    rm jasper-{{version}}.tar.gz

    # build OUTSIDE the source tree to avoid "InSourceBuild" logic and double 'build/' paths
    rm -rf build-jasper
    mkdir -p build-jasper

    # make sure CC/CXX/CFLAGS are applied to the first configure
    {{gclang_config}} cmake -S jasper -B build-jasper -G Ninja \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX="$PWD/jasper/install" \
        -DJAS_ENABLE_PROGRAMS=ON \
        -DJAS_ENABLE_SHARED=OFF

    ninja -C build-jasper -j"$(nproc)"
    ninja -C build-jasper install

    get-bc "$PWD/jasper/install/bin/jasper"

