
gclang_config := 'CC=gclang CXX=gclang++ CFLAGS="-g -O0 -Xclang -disable-O0-optnone"'

gnumake version="4.4":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "gnumake" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/make/make-{{version}}.tar.gz
        tar zxf make-{{version}}.tar.gz
        mv make-{{version}} gnumake
        rm make-{{version}}.tar.gz
    fi
    pushd gnumake
        ./configure {{gclang_config}} --prefix=$PWD/install
        make -j $(nproc)
        make install
        get-bc $PWD/install/bin/make
    popd

lua version="5.4.8":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "lua" ]; then
        curl -fL -O https://www.lua.org/ftp/lua-{{version}}.tar.gz
        tar zxf lua-{{version}}.tar.gz
        mv lua-{{version}} lua
        rm lua-{{version}}.tar.gz
    fi
    pushd lua
        make clean
        make -j $(nproc) posix {{gclang_config}}
        make install INSTALL_TOP=$PWD/install
        get-bc $PWD/install/bin/lua
    popd

openssl version="3.5.4":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "openssl" ]; then
        curl -fL -O https://github.com/openssl/openssl/releases/download/openssl-{{version}}/openssl-{{version}}.tar.gz
        tar zxf openssl-{{version}}.tar.gz
        mv openssl-{{version}} openssl
        rm openssl-{{version}}.tar.gz
    fi
    pushd openssl
        {{gclang_config}} ./Configure  --prefix=$PWD/install no-shared no-module enable-tls1_3 enable-rc5 enable-md2 enable-ec_nistp_64_gcc_128 enable-ssl3
        make -j $(nproc)
        make -j $(nproc) install
    popd

# bc (GNU bc)
bc version="1.07.1":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "bc-src" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/bc/bc-{{version}}.tar.gz
        tar zxf bc-{{version}}.tar.gz
        mv bc-{{version}} bc-src
        rm bc-{{version}}.tar.gz
    fi
    pushd bc-src
        {{gclang_config}}
        ./configure --prefix=$PWD/install --disable-shared
        make clean
        make -j $(nproc)
        make -j $(nproc) install
        get-bc "$PWD/install/bin/bc"
    popd

# tic (from ncurses)
tic version="6.4":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "ncurses" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/ncurses/ncurses-{{version}}.tar.gz
        tar zxf ncurses-{{version}}.tar.gz
        mv ncurses-{{version}} ncurses
        rm ncurses-{{version}}.tar.gz
    fi
    pushd ncurses
        {{gclang_config}} ./configure  --with-termlib --without-debug --prefix=$PWD/install
        make -j "$(nproc)"
        make install
        get-bc "$PWD/install/bin/tic"
    popd

bison version="3.8.2":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "bison" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/bison/bison-{{version}}.tar.gz
        tar zxf bison-{{version}}.tar.gz
        mv bison-{{version}} bison
        rm bison-{{version}}.tar.gz
    fi
    pushd bison
        {{gclang_config}} ./configure --prefix=$PWD/install
        make -j "$(nproc)"
        make install
        get-bc "$PWD/install/bin/bison"
    popd
  
# readelf and strip (from binutils)
binutils version="2.42":
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d "binutils" ]; then
        curl -fL -O https://mirrors.ibiblio.org/gnu/binutils/binutils-{{version}}.tar.xz
        tar Jxf binutils-{{version}}.tar.xz
        mv binutils-{{version}} binutils
        rm binutils-{{version}}.tar.xz
    fi
    pushd binutils
        {{gclang_config}}
        ./configure --disable-werror --prefix=$PWD/install
        make -j "$(nproc)"
        make install
        get-bc "$PWD/install/bin/readelf"
        get-bc "$PWD/install/bin/strip"
    popd
