##===- unittests/Solver/Makefile ---------------------------*- Makefile -*-===##

LEVEL := ../..
TESTNAME := Solver
USEDLIBS := kleaverSolver.a kleaverExpr.a kleeSupport.a kleeBasic.a
LINK_COMPONENTS := support

include $(LEVEL)/Makefile.config
include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest

LIBS += -lstp 
