#!/bin/bash
####################
# git clone it !!! #
####################
git clone --depth 1 --branch 2.1.2 https://github.com/stp/stp.git

#################################
# No changes will be needed ... #
#################################
rm -rf stp/.git

################################
# Get inside the stp directory #
################################
cd stp

#############################################
# mkdir a build directory and get inside it #
#############################################
mkdir build && cd build

#########
# cmake #
#########
cmake                                                            \
-DBUILD_SHARED_LIBS:BOOL=OFF                                     \
-DENABLE_PYTHON_INTERFACE:BOOL=OFF                               \
-DMINISAT_INCLUDE_DIR="../../minisat/"                           \
-DMINISAT_LIBRARY="../../minisat/build/release/lib/libminisat.a" \
-DCMAKE_BUILD_TYPE="Release"                                     \
-DTUNE_NATIVE:BOOL=ON ..

###############
# make it !!! #
###############
make -j `nproc`

