#!/bin/bash
#########
# FILES #
#########
INPUT_FILE=$1
OUTPUT_FILE=$2

####################
# HELPER VARIABLES #
####################
DIGIT="\([0-9]\)"

####################
# HELPER VARIABLES #
####################
SIZE="\([0-9]\)"
CHAR="\('[a-zA-Z]'\)"
ZERO="0"

####################
# HELPER VARIABLES #
####################
pVar="p$DIGIT"
rVar="r$DIGIT"
iVar="i$DIGIT"
cVar="c$DIGIT"
Idx="\([0-9]\)"

####################
# HELPER VARIABLES #
####################
ASSIGN="\( *= *\)"
PLUS="\( *+ *\)"

####################
# HELPER VARIABLES #
####################
CONST_STRING="\(\"[^\"]*\"\)"

######################
# ACTUAL SED COMMAND #
######################
sed                                                                                        \
-e "s/${pVar}${ASSIGN}malloc($SIZE)/MyMalloc(p\1, \3)/g"                                   \
-e "s/${pVar}${ASSIGN}malloc($iVar)/MyMalloc(p\1,i\3)/g"                                   \
-e "s/${pVar}\[$Idx\]${ASSIGN}${CHAR}/MyWriteConstCharToStringAtConstOffset(p\1,\2,\4)/g"  \
-e "s/${pVar}\[$Idx\]${ASSIGN}${cVar}/MyWriteCharToStringAtOffset( p\1, \2,c\4)/g"         \
-e "s/${pVar}\[$Idx\]${ASSIGN}${ZERO}/MyWriteConstCharToStringAtConstOffset(p\1,\2,0)/g"   \
-e "s/${pVar}\[$iVar\]${ASSIGN}${CHAR}/MyWriteConstCharToStringAtOffset(p\1,i\2,\4)/g"     \
-e "s/${pVar}\[$iVar\]${ASSIGN}${cVar}/MyWriteCharToStringAtOffset(p\1,i\2,c\4)/g"         \
-e "s/${pVar}\[$iVar\]${ASSIGN}${ZERO}/MyWriteConstCharToStringAtOffset(p\1,i\2, 0)/g"     \
-e "s/${rVar}${ASSIGN}${CONST_STRING}/MyConstStringAssign(r\1,\3)/g"                       \
-e "s/${pVar}${ASSIGN}${pVar}${PLUS}${iVar}/MyStringAssignWithOffset(p\1,p\3,i\5)/g"       \
-e "s/${pVar}${ASSIGN}${pVar}${PLUS}${DIGIT}/MyStringAssignWithConstOffset(p\1,p\3,i\5)/g" \
-e "s/${pVar}/OISH_p\1/g" \
-e "s/${rVar}/OISH_r\1/g" \
-e "s/${cVar}/OISH_c\1/g" \
-e "s/${iVar}/OISH_i\1/g" \
${INPUT_FILE} > ${OUTPUT_FILE}
