# Makefile to build and run the examples using KLEE.
#
# Copyright 2015 National University of Singapore

TARGETS=addition_safe1.klee \
	addition_safe2.klee \
	addition_unsafe.klee

include Makefile.common

